INSERT INTO subcategory (subcategory_name, category_id) VALUES
('All-purpose', 4),
('Aluminum Foil',10),
('Baby Items',9),
('Beef',8),
('Bread',1),
('Packed Bread',7),
('Butter',5),
('Cereals',6),
('Cheese',5),
('Coffee',2),
('Condiments & Dressings',3),
('Conditioner',11),
('Cooking Ingredients',3),
('Deodorant',11),
('Dishwashing',4),
('Eggs',5),
('Flour',6),
('Food Storage',10),
('Fruits',12),
('Fruits & Vegetables',7),
('Greeting Cards',9),
('Ice Cream',7),
('Juice',2),
('Laundry',4),
('Meals',7),
('Milk',5),
('Mixes',6),
('Packed Foods',3),
('Paper Towels',10),
('Pastries',1),
('Pet Items',9),
('Pork',8),
('Poultry',8),
('Seafood',8),
('Shampoo',11),
('Shaving Cream',11),
('Soap',11),
('Soda',2),
('Sugar',6),
('Tea',2),
('Toilet Paper',10),
('Tortillas',1),
('Vergetable',12),
('Yogurt',5);